on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Send repo to Dataverse 
        uses: IQSS/dataverse-uploader@v1.4
        with:
          DATAVERSE_TOKEN: ${{secrets.GRO_DATA_TOKEN}}
          DATAVERSE_SERVER: https://data.goettingen-research-online.de/
          DATAVERSE_DATASET_DOI:  doi:10.25625/BWHIHA
          DELETE: True
          PUBLISH: True
